#!/usr/bin/env python3
"""Generate `docs/plans/solve/book.md` — the human-readable refutation
book (plan10 task 4, the bounded docs-only side task pending since
2026-09-23).

Source: the committed `measurements/plan4/state/p2_*.json` records (400
ply-2 runs of the report4 density screen, each with outcome + PV).  Output
structure = report4 §1 expanded per first move with PVs and node costs.
Verification: the generated counts must match report4 §1 (55 decided;
17/13/13/11/1 per-move table) — the script aborts on any mismatch.

Moves are UCI (machine-checkable against the FENs in the source records);
each refutation line is `1.<first> <reply> 2.<pv...>` from the start
position.
"""

from __future__ import annotations

import glob
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
P2 = os.path.abspath(os.path.join(HERE, "..", "plan4", "state"))
BOOK = os.path.abspath(os.path.join(HERE, "..", "..", "book.md"))

# report4 §1 per-move refutation counts (the verification target).
REPORT4_TABLE = {"g1f3": 17, "e2e4": 13, "e2e3": 13, "g1h3": 11, "c2c3": 1}


def san_ish(mv: str) -> str:
    """UCI long algebraic, piece-letter decorated (readable, unambiguous
    without a board: the origin+target squares identify the move)."""
    if len(mv) == 5:  # promotion, e.g. e7e8q
        return f"{mv[0]}{mv[1]}-{mv[2]}{mv[3]}={mv[4].upper()}"
    return f"{mv[0]}{mv[1]}-{mv[2]}{mv[3]}"


def move_seq(moves):
    """`a2a3 a7a5 d1h5...` -> `1.a2-a3 a7-a5 2.d1-h5 ...`"""
    out, num = [], 1
    for i, mv in enumerate(moves):
        if i % 2 == 0:
            out.append(f"{num}.")
        out.append(san_ish(mv))
        if i % 2 == 1:
            num += 1
    return " ".join(out)


def main():
    recs = []
    for f in sorted(glob.glob(os.path.join(P2, "p2_*.json"))):
        with open(f) as fh:
            recs.append(json.load(fh))
    if len(recs) != 400:
        sys.exit(f"expected 400 p2 records, found {len(recs)}")
    decided = [r for r in recs if r["outcome"] in ("win", "loss")]
    for r in decided:
        if r["outcome"] != "win":
            sys.exit(f"unexpected non-win decided record: {r['tag']}")
        if not r["pv"]:
            sys.exit(f"decided record without PV: {r['tag']}")

    by_first = {}
    for r in recs:
        by_first.setdefault(r["moves"][0], []).append(r)

    counts = {}
    for m, rs in by_first.items():
        counts[m] = sum(1 for r in rs if r["outcome"] == "win")
    for m, n in REPORT4_TABLE.items():
        if counts.get(m) != n:
            sys.exit(f"verification FAILED: {m} refuted {counts.get(m)} "
                     f"(report4 §1: {n})")
    others = {m: n for m, n in counts.items() if m not in REPORT4_TABLE}
    if any(n != 0 for n in others.values()):
        sys.exit(f"verification FAILED: unexpected refutations {others}")
    if sum(counts.values()) != 55:
        sys.exit("verification FAILED: total != 55")

    lines = []
    lines.append("# Atomic chess refutation book — Black's first replies\n")
    lines.append(
        "Human-readable rendering of the plan4 density-screen artifact "
        "(report4 §1 expanded): every cheap forced win against a second "
        "move at the start position, with its principal variation and "
        "search-node cost.\n")
    lines.append(
        "**Provenance.** Source data: `docs/plans/solve/measurements/"
        "plan4/state/p2_*.json` (400 runs, 8 s screen, `--first-outcome`, "
        "release build at report4's recorded commit); generated by "
        "`docs/plans/solve/measurements/plan10/make_book.py` (plan10 task "
        "4), which verifies the counts against report4 §1 before "
        "writing.\n")
    lines.append(
        "**Reading.** Moves are given in long algebraic (UCI squares, "
        "origin-target; `=` marks promotion). Each line is a full "
        "principal variation from the start position: White's first move, "
        "Black's reply, then White's forced win (all 55 refutations are "
        "White wins; outcome + PV as returned by the solver). `nodes` is "
        "the search cost at which the win was proven (screen budget 8 s).\n")
    lines.append(
        "**Scope caveat (report4 §2/§3).** This book is the measured, "
        "saturated cheap class — one-sided and patterned (queen–bishop "
        "diagonals only). The remaining 345 ply-2 positions and all 20 "
        "ply-1 positions are the quiet plateau class (promotion sample: "
        "still censored at 120 s, ~20–23.5M nodes); the book is "
        "self-contained at startpos and does not reach the ladder's deep "
        "tactical wins.\n")

    order = sorted(by_first, key=lambda m: (-counts[m], m))
    lines.append("## Summary (verification = report4 §1)\n")
    lines.append("| first move | refuted | of | decided |")
    lines.append("| --- | --- | --- | --- |")
    for m in order:
        n = counts[m]
        if n:
            lines.append(f"| 1.{san_ish(m)} | **{n}** | 20 | win |")
    zero = [m for m in order if counts[m] == 0]
    lines.append(f"| the other {len(zero)} first moves | 0 | 200 | — |")
    lines.append("")
    lines.append(f"**55 decided / 400 ply-2 positions (13.75%); "
                 f"{len(zero)} first moves refute nothing.**\n")

    for m in order:
        n = counts[m]
        rs = by_first[m]
        rs.sort(key=lambda r: r["moves"][1])
        if n:
            lines.append(f"## 1.{san_ish(m)} — refutes {n}/20\n")
            lines.append("| reply | refutation (PV from startpos) | nodes |")
            lines.append("| --- | --- | --- |")
            for r in rs:
                if r["outcome"] == "win":
                    seq = move_seq(r["moves"] + r["pv"])
                    lines.append(f"| {san_ish(r['moves'][1])} | {seq} | "
                                 f"{r['nodes']:,} |")
        else:
            lines.append(f"## 1.{san_ish(m)} — refutes 0/20\n")
        undecided = [san_ish(r["moves"][1]) for r in rs
                     if r["outcome"] not in ("win", "loss")]
        if n < 20:
            lines.append("")
            lines.append(f"Undecided at the screen budget "
                         f"({20 - n} of 20): {', '.join(undecided)}.\n")
    with open(BOOK, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"book written: {BOOK}")
    print("verification: 55 decided;", {m: counts[m] for m in REPORT4_TABLE},
          "— matches report4 §1")


if __name__ == "__main__":
    main()
